In [1]:
import torch
import numpy as np

# 创建张量的基本方法
print("===== 创建张量的基本方法 =====")
# 从列表创建张量
tensor1 = torch.tensor([1, 2, 3, 4])
print(f"从列表创建张量: {tensor1}")

# 创建全0张量
zeros = torch.zeros(3, 4)
print(f"全0张量:\n{zeros}")

# 创建全1张量
ones = torch.ones(2, 3)
print(f"全1张量:\n{ones}")

# 创建随机张量
random_tensor = torch.rand(2, 2)
print(f"随机张量:\n{random_tensor}")

# 创建指定范围的张量
range_tensor = torch.arange(0, 10, 2)
print(f"范围张量: {range_tensor}")

# 从NumPy数组创建张量
numpy_array = np.array([[1, 2], [3, 4]])
tensor_from_numpy = torch.from_numpy(numpy_array)
print(f"从NumPy创建张量:\n{tensor_from_numpy}")

# 张量的属性
print("\n===== 张量的属性 =====")
x = torch.rand(3, 4)
print(f"张量: \n{x}")
print(f"形状: {x.shape}")
print(f"数据类型: {x.dtype}")
print(f"设备: {x.device}")

# 张量操作
print("\n===== 张量操作 =====")
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# 加法
print(f"a + b = {a + b}")
print(f"torch.add(a, b) = {torch.add(a, b)}")

# 乘法
print(f"a * b = {a * b}")  # 元素级乘法
print(f"torch.mul(a, b) = {torch.mul(a, b)}")

# 矩阵乘法
m1 = torch.tensor([[1, 2], [3, 4]])
m2 = torch.tensor([[5, 6], [7, 8]])
print(f"矩阵乘法:\n{torch.matmul(m1, m2)}")

# 改变张量形状
c = torch.arange(12)
print(f"原始张量: {c}")
print(f"重塑为3x4: \n{c.reshape(3, 4)}")
print(f"转置: \n{c.reshape(3, 4).t()}")

# 索引和切片
print("\n===== 索引和切片 =====")
d = torch.arange(12).reshape(3, 4)
print(f"张量d:\n{d}")
print(f"第一行: {d[0]}")
print(f"第一列: {d[:, 0]}")
print(f"子矩阵: \n{d[1:3, 1:3]}")

# 张量与GPU
print("\n===== 张量与GPU =====")
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("CUDA可用，可以使用GPU")
    tensor_gpu = torch.tensor([1, 2, 3], device=device)
    print(f"GPU上的张量: {tensor_gpu}")
    
    # 将CPU张量移到GPU
    tensor_cpu = torch.tensor([4, 5, 6])
    tensor_gpu = tensor_cpu.to(device)
    print(f"移到GPU的张量: {tensor_gpu}")
else:
    print("CUDA不可用，只能使用CPU")

# 自动微分
print("\n===== 自动微分 =====")
x = torch.tensor([2.0], requires_grad=True)
y = x**2 + 2*x + 1
print(f"y = x^2 + 2x + 1, 当x={x.item()}时, y={y.item()}")
y.backward()
print(f"dy/dx = 2x + 2 = {x.grad.item()}")


===== 创建张量的基本方法 =====
从列表创建张量: tensor([1, 2, 3, 4])
全0张量:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
全1张量:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
随机张量:
tensor([[0.9591, 0.8429],
        [0.2373, 0.1891]])
范围张量: tensor([0, 2, 4, 6, 8])
从NumPy创建张量:
tensor([[1, 2],
        [3, 4]])

===== 张量的属性 =====
张量: 
tensor([[0.9645, 0.4443, 0.3963, 0.6476],
        [0.5959, 0.6598, 0.6578, 0.0950],
        [0.6082, 0.8567, 0.0154, 0.6419]])
形状: torch.Size([3, 4])
数据类型: torch.float32
设备: cpu

===== 张量操作 =====
a + b = tensor([5, 7, 9])
torch.add(a, b) = tensor([5, 7, 9])
a * b = tensor([ 4, 10, 18])
torch.mul(a, b) = tensor([ 4, 10, 18])
矩阵乘法:
tensor([[19, 22],
        [43, 50]])
原始张量: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
重塑为3x4: 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
转置: 
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

===== 索引和切片 =====
张量d:
tensor([[ 0,  1,