In [1]:
import numpy as np

# 一维二维数组的创建

In [2]:
oneArray = np.arange(0, 10)
print(oneArray)
print(type(oneArray))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [3]:
twoArray = np.arange(0,24,2).reshape(6,2)
print(twoArray)
print(twoArray.shape)

[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]
 [20 22]]
(6, 2)


# 常用属性

In [4]:
list1 = [[1,2],[3,4],[5,6]]
text_array = np.array(list1)
print(text_array.ndim)
print(text_array.shape)
print(text_array.size)

2
(3, 2)
6


# 形状调整

In [5]:
text_array.shape = (2,3)
print(text_array)

print(text_array.reshape(3,2))

text1 = text_array.reshape((6,),order='F')
text2 = text_array.reshape((6,))
print(text1)
print(text2)

text3 = np.arange(12)
print(text3)
text3.shape = (3,4)
print(text3)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 4 2 5 3 6]
[1 2 3 4 5 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# python list的互相

In [6]:
text3_list = text3.tolist()
print(text3_list)
print(type(text3_list))

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
<class 'list'>


# 数据类型

In [7]:
import random
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize) 
print(f.dtype)
f1 = f.astype(np.int64)
print(f1.dtype)
print(round(random.random(),2))
arr = np.array([random.random() for i in range(10)])
print(np.round(arr,2))

2
int16
int64
0.94
[0.6  0.66 0.38 0.03 1.   0.14 0.15 0.33 0.03 0.59]


# 数组和数的计算

In [8]:
t1 =np.arange(24).reshape((6,4))
print(t1)
print("-"*20)
print(t1+2)
print("-"*20)
print(t1*2)
print("-"*20)
print(t1/2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


# 数组与数组之间的操作

In [9]:
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))
print(t1)
print(t2)
print("-"*20)
print(t1+t2)
print(t1*t2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [10]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6)
print(t1)
print("-"*20)
print(t2)
print("-"*20)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[0 1 2 3 4 5]
--------------------
[[ 0  0  0  0  0  0]
 [ 6  6  6  6  6  6]
 [12 12 12 12 12 12]
 [18 18 18 18 18 18]]


In [11]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(4).reshape((4,1))
print(t1)
print("-"*20)
print(t2)
print("-"*20)
print(t1-t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[[0]
 [1]
 [2]
 [3]]
--------------------
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


# 数组的轴

In [12]:
a = np.arange(24).reshape(3,8)
print(a)
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(np.sum(a))
print("-"*20)
a.shape = (2,3,4)
print(a)
print("-"*20)
b = np.sum(a, axis=0)
print(b)
print("-"*20)
c = np.sum(a,axis=1)
print(c)
d = np.sum(a,axis=2)
print(d)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[24 27 30 33 36 39 42 45]
[ 28  92 156]
276
--------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
--------------------
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


# 数组的索引和切片

In [13]:
t = np.arange(24).reshape(4,6)
print(t)
print('*'*20)
print(t[1]) # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*'*20)
print(t[1:])# 取连续的多行
print('*'*20)
print(t[1:3,:])# 取连续的多行
print('*'*20)
print(t[[0,2,3]])# 取不连续的多行
print('*'*20)
print(t[[0,2,3],:])# 取不连续的多行
print('*'*20)
print(t[:,1])# 取一列
print('*'*20)
print(t[:,1:])# 连续的多列
print('*'*20)
print(t[:,[0,2,3]])# 取不连续的多列
print('*'*20)
print(t[2,3])# # 取某一个值,三行四列
print('*'*20)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************


# 数组中的数值修改

In [14]:
t[1, :] = 0
print(t)
t[:, 1] = 0
print(t)
t[1:3, :] = 0
print(t)
t[:, 1:4] = 0
print(t)
t[t < 10] = 0
print(t)

[[ 0  1  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12  0 14 15 16 17]
 [18  0 20 21 22 23]]
[[ 0  0  2  3  4  5]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0 20 21 22 23]]
[[ 0  0  0  0  4  5]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0  0 22 23]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0  0 22 23]]


# 数组的添加

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print('-'*20)
print(np.append(a, [7, 8, 9]))
print('-'*20)
print(np.append(a, [[7, 8, 9]], axis=0))
print('-'*20)
print(np.append(a, [[7, 8, 9], [9, 9, 9]], axis=1))
print('-'*20)
print(np.insert(a, 1, [11, 12]))
print('-'*20)
print(np.insert(a, 1, [11, 12, 13], axis=0))
print('-'*20)
print(np.insert(a, 1, [11, 12], axis=1))

[[1 2 3]
 [4 5 6]]
--------------------
[1 2 3 4 5 6 7 8 9]
--------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[[1 2 3 7 8 9]
 [4 5 6 9 9 9]]
--------------------
[ 1 11 12  2  3  4  5  6]
--------------------
[[ 1  2  3]
 [11 12 13]
 [ 4  5  6]]
--------------------
[[ 1 11  2  3]
 [ 4 12  5  6]]


# 数组的连接，堆叠

In [16]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concatenate((a,b),axis=0))
print('-'*20)
print(np.concatenate((a,b),axis=1))
print('-'*50)
print(np.stack((a,b),axis=0))
print('-'*20)
print(np.stack((a,b),axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------
[[1 2 5 6]
 [3 4 7 8]]
--------------------------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------------
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


# nan和inf的使用

In [17]:
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))
t = np.arange(24,dtype=float).reshape(4,6)
print(t)
t[2,3] = np.nan
print('-'*20)
print(t)
print(np.count_nonzero(t))
print(np.count_nonzero(t != t))
print('-'*20)
t[np.isnan(t)] = 0
print(t)
print('-'*20)
t[1,3:] = np.nan
print(t)
print('-'*20)
for i in range(t.shape[1]):
    temp_col = t[:i]
    nan_num = np.count_nonzero(temp_col != temp_col)
    if nan_num != 0:
        temp_col_not_nan = temp_col[temp_col == temp_col]
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)
print(t)

nan <class 'float'>
inf <class 'float'>
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. nan 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
23
1
--------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14.  0. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14.  0. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  4.  4.  4.]
 [12. 13. 14.  0. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


# 组转置，轴滚动

In [27]:
a = np.arange(12).reshape(3,4)
print(a)
print('-'*20)
print (np.transpose(a))
print('-'*20)
print(a.T)
print('-'*20)
t = np.arange(24).reshape(4,6)
print(t)
print('-'*20)
re = t.swapaxes(0,1)
print(re)
print('-'*20)
t.shape = (2,3,4)
print(t)
re = t.swapaxes(0,2)
print(re)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
--------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
--------------------
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--------------------
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
--------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
