In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
us_file_path = "./youtube_video_data/US_video_data_numbers.csv"
uk_file_path = "./youtube_video_data/GB_video_data_numbers.csv"
t1 = np.loadtxt(us_file_path,delimiter=",",dtype="int",unpack=True)
t2 = np.loadtxt(us_file_path,delimiter=",",dtype="int")

In [3]:
print(t1)
print("*"*100)
print(t2)

[[4394029 7860119 5845909 ...  142463 2162240  515000]
 [ 320053  185853  576597 ...    4231   41032   34727]
 [   5931   26679   39774 ...     148    1384     195]
 [  46245       0  170708 ...     279    4737    4722]]
****************************************************************************************************
[[4394029  320053    5931   46245]
 [7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]


In [4]:
print(t2[2])

[5845909  576597   39774  170708]


In [5]:
print(t2[2:])

[[5845909  576597   39774  170708]
 [2642103   24975    4542   12829]
 [1168130   96666     568    6666]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]


In [6]:
b = t2[2:5,1:4]
print(b)

[[576597  39774 170708]
 [ 24975   4542  12829]
 [ 96666    568   6666]]


In [8]:
c = t2[[0,2,2],[0,1,3]]
c

array([4394029,  576597,  170708])

In [12]:
t_us = np.loadtxt(us_file_path,delimiter=",",dtype="int")
t_us_comments = t_us[:,-1]
t_us_comments = t_us_comments[t_us_comments<=5000]
print(t_us_comments.max(),t_us_comments.min())

4995 0


In [13]:
d = 50
bin_nums = (t_us_comments.max()-t_us_comments.min())//d

In [14]:
plt.figure(figsize=(20,8),dpi=800)
plt.hist(t_us_comments,bin_nums)
plt.show()

In [20]:
t_uk = np.loadtxt(uk_file_path,delimiter=",",dtype="int")
t_uk = t_uk[t_uk[:,1]<=500000]
t_uk_comment = t_uk[:,-1]
t_uk_like = t_uk[:,1]
plt.figure(figsize=(20,8),dpi=800)
plt.scatter(t_uk_like,t_uk_comment)
plt.show()